### ISSUE TITLE
User Registration Error

### ISSUE THREAD

**Issue by Tridence** [rahulhegde99/Online-Crime-Management#1]
Fatal error: Uncaught TypeError: mysqli_select_db(): Argument #1 ($mysql) must be of type mysqli, string given in C:\xampp\htdocs\Crime-Reporting-System\registration.php:21 Stack trace: #0 C:\xampp\htdocs\Crime-Reporting-System\registration.php(21): mysqli_select_db('crime_portal', Object(mysqli)) #1 {main} thrown in C:\xampp\htdocs\Crime-Reporting-System\registration.php on line 21

**Comment by rahulhegde99** [comment]
This particular codebase runs on PHP 5.0. However I see you've tried to migrate it to PHP7, which is syntactically
`mysqli_select_db($mysqli_object, $dbname)`
I think you've interchanged the parameters.

**Comment by Tridence** [comment]
I have actually solved the error; Interchanging the parameters makes the code run smoothly. Thanks man.
